
package Formularios;

import Formularios.PantallaInicio;
import com.sun.prism.paint.Color;
import Formularios.PantallaInicio;
import javax.swing.JOptionPane;
/**
 *
 * @author HP 9480m
 */
public class JugadorVrss extends javax.swing.JFrame {

private String turno="X";
    public JugadorVrss() {
        initComponents();
        setSize(1000,600);
        transparencia();
        setLocationRelativeTo(null);
 
       
    }
    private void ganadorx(){
        
        JOptionPane.showMessageDialog(null,"El ganador es : X ","FELICIDADES", JOptionPane.INFORMATION_MESSAGE);
    }
     private void ganadorO(){
        
        JOptionPane.showMessageDialog(null,"El ganador es: O ","FELICIDADES", JOptionPane.INFORMATION_MESSAGE);
    }
    public void transparencia(){
    jButton1.setOpaque(false);
    jButton1.setContentAreaFilled(false);
    jButton1.setBorderPainted(false);
    jButton2.setOpaque(false);
    jButton2.setContentAreaFilled(false);
    jButton2.setBorderPainted(false);
    jButton3.setOpaque(false);
    jButton3.setContentAreaFilled(false);
    jButton3.setBorderPainted(false);
    jButton4.setOpaque(false);
    jButton4.setContentAreaFilled(false);
    jButton4.setBorderPainted(false);
    jButton5.setOpaque(false);
    jButton5.setContentAreaFilled(false);
    jButton5.setBorderPainted(false);
    jButton6.setOpaque(false);
    jButton6.setContentAreaFilled(false);
    jButton6.setBorderPainted(false);
    jButton7.setOpaque(false);
    jButton7.setContentAreaFilled(false);
    jButton7.setBorderPainted(false);
    jButton8.setOpaque(false);
    jButton8.setContentAreaFilled(false);
    jButton8.setBorderPainted(false);
    jButton9.setOpaque(false);
    jButton9.setContentAreaFilled(false);
    jButton9.setBorderPainted(false);
     
    
    }
    private void seleccionxo(){
       if(turno.equalsIgnoreCase("X")) {
           turno="0";
       }
       else{
           turno="X";
       }
    }
    private void determinarGanado(){
        String uno =jButton1.getText();
        String dos =jButton2.getText();
        String tres =jButton3.getText();
        String cuatro =jButton4.getText();
        String cinco =jButton5.getText();
        String seis=jButton6.getText();
        String siete=jButton7.getText();
        String ocho=jButton8.getText();
        String nueve=jButton9.getText();
       if(uno.equals("X")&& dos.equals("X")&& tres.equals("X") ){
        ganadorx();
        return;
        } else if(cuatro.equals("X")&& cinco.equals("X")&& seis.equals("X")){
          ganadorx();
           return;
        } else if(siete.equals("X")&&ocho.equals("X")&& nueve.equals("X")){
           ganadorx();
           return;
        } else if(uno.equals("X")&&cuatro.equals("X")&& siete.equals("X")) {
           ganadorx();
          return;
        } else if (dos.equals("X")&&cinco.equals("X")&&ocho.equals("X")){
          ganadorx();  
          return;
        }else if(tres.equals("X")&& seis.equals("X")&& nueve.equals("X")){
         ganadorx(); 
          return;
        } else if(uno.equals("X")&&cinco.equals("X")&& nueve.equals("X")){
            ganadorx();
          return;
        }else if(tres.equals("X") && cinco.equals("X") && siete.equals("X")){
            ganadorx(); 
          return;
        } //Evaluacion para 0
        else if(uno.equals("0")&& dos.equals("0")&& tres.equals("0") ){
             ganadorO();
          return;
        } else if(cuatro.equals("0")&&(cinco.equals("0") && seis.equals("0"))){
          ganadorO();
          return;
        } else if(siete.equals("0")&&(ocho.equals("0")&& nueve.equals("0"))){
         ganadorO();
         return;
        } else if(uno.equals("0")&&(cuatro.equals("0")&&(siete.equals("0")))) {
          ganadorO();
         return;
        } else if (dos.equals("0")&&(cinco.equals("0")&&(ocho.equals("0")))){
         ganadorO();
        return;
        }else if(tres.equals("0")&&(seis.equals("0")&&nueve.equals("0"))){
         ganadorO();
        return;
        }else if(uno.equals("0")&&cinco.equals("0")&& nueve.equals("0")){
        ganadorO();
        return;
        }else if(tres.equals("0") && cinco.equals("0") && siete.equals("0")){
        ganadorO();
         return;
        } 
    }
    
 
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        Salir = new javax.swing.JToggleButton();
        Reiniciar = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Arial", 1, 65)); // NOI18N
        jButton1.setMargin(new java.awt.Insets(5, 14, 2, 14));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 60, 100, 100);

        jButton2.setFont(new java.awt.Font("Arial", 1, 65)); // NOI18N
        jButton2.setMargin(new java.awt.Insets(5, 14, 2, 14));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 60, 100, 100);

        jButton3.setFont(new java.awt.Font("Arial", 1, 65)); // NOI18N
        jButton3.setMargin(new java.awt.Insets(5, 14, 2, 14));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(420, 60, 100, 100);

        jButton4.setFont(new java.awt.Font("Arial", 1, 65)); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(60, 230, 100, 100);

        jButton5.setFont(new java.awt.Font("Arial", 1, 65)); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(250, 230, 100, 100);

        jButton6.setFont(new java.awt.Font("Arial", 1, 65)); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(420, 230, 100, 100);

        jButton7.setFont(new java.awt.Font("Arial", 1, 65)); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(60, 400, 100, 100);

        jButton8.setFont(new java.awt.Font("Arial", 1, 65)); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(250, 400, 100, 100);

        jButton9.setFont(new java.awt.Font("Arial", 1, 65)); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(420, 400, 100, 100);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setText("Regresar a menu");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(700, 430, 200, 60);

        Salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir);
        Salir.setBounds(700, 290, 200, 60);

        Reiniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Reiniciar.setText("Reiniciar");
        Reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(Reiniciar);
        Reiniciar.setBounds(700, 360, 200, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondovrs1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 990, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jButton4.setText(turno);
         seleccionxo();
          if(turno.equalsIgnoreCase("X")){
        jButton4.setForeground(java.awt.Color.WHITE);
     }else
     {
          jButton4.setForeground(java.awt.Color.red);
     }
               determinarGanado();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
         System.exit(WIDTH);
    }//GEN-LAST:event_SalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton1.setText(turno);
        seleccionxo();
     if(turno.equalsIgnoreCase("X")){
        jButton1.setForeground(java.awt.Color.WHITE);
     }else
     {
          jButton1.setForeground(java.awt.Color.red);
     }
     determinarGanado();
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton2.setText(turno);
       seleccionxo();
        if(turno.equalsIgnoreCase("X")){
        jButton2.setForeground(java.awt.Color.WHITE);
     }else
     {
          jButton2.setForeground(java.awt.Color.red);
     }
             determinarGanado();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         jButton3.setText(turno);
     seleccionxo();
      if(turno.equalsIgnoreCase("X")){
        jButton3.setForeground(java.awt.Color.WHITE);
     }else
     {
          jButton3.setForeground(java.awt.Color.red);
     }
           determinarGanado();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         jButton5.setText(turno);
       seleccionxo();
        if(turno.equalsIgnoreCase("X")){
        jButton5.setForeground(java.awt.Color.WHITE);
     }else
     {
          jButton5.setForeground(java.awt.Color.red);
     }
             determinarGanado();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jButton6.setText(turno);
       seleccionxo();
        if(turno.equalsIgnoreCase("X")){
        jButton6.setForeground(java.awt.Color.WHITE);
     }else
     {
          jButton6.setForeground(java.awt.Color.red);
     }
                  determinarGanado();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jButton7.setText(turno);
       seleccionxo();
        if(turno.equalsIgnoreCase("X")){
        jButton7.setForeground(java.awt.Color.WHITE);
     }else
     {
          jButton7.setForeground(java.awt.Color.red);
     }
             determinarGanado();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jButton8.setText(turno);
       seleccionxo();
        if(turno.equalsIgnoreCase("X")){
        jButton8.setForeground(java.awt.Color.WHITE);
    }else
     {
          jButton8.setForeground(java.awt.Color.red);
     }
             determinarGanado();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         jButton9.setText(turno);
           seleccionxo();
         if(turno.equalsIgnoreCase("X")){
        jButton9.setForeground(java.awt.Color.WHITE);
     }else
     {
          jButton9.setForeground(java.awt.Color.red);
     }
         
              determinarGanado();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void ReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReiniciarActionPerformed
        // TODO add your handling code here:
          boolean hola =true;
         jButton1.setText("");
         jButton2.setText("");
         jButton3.setText("");
         jButton4.setText("");
         jButton5.setText("");
        jButton6.setText("");
        jButton7.setText("");
        jButton8.setText("");
        jButton9.setText("");
    }//GEN-LAST:event_ReiniciarActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       PantallaInicio regresar =new PantallaInicio();
       regresar.setVisible(true);
       this.dispose();
         
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JugadorVrss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JugadorVrss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JugadorVrss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JugadorVrss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JugadorVrss().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Reiniciar;
    private javax.swing.JToggleButton Salir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
